Table updates, Scraper Addition
DavidPHH/Drink-Macro-Creator pull request #7
Opened 2023-06-04 22:58 UTC by EricaPomme

As noted in the committed changelog, this brings a few more updates. Namely, the drink table has been recreated with values from Wowhead as of 2023/06/04, and a new directory has been added with a tool to easily create properly formatted lines. It's a bit of a quick and dirty tool; I probably could have spent the time I spent writing out the readme making it an all-in-one does-everything table generator but I never claimed to be clever. :)
<img width="1038" alt="CleanShot 2023-06-04 at 09 01 46@2x" src="https://github.com/DavidPHH/Drink-Macro-Creator/assets/27747481/25dda0e8-fd6f-4092-943b-a35a17d5b816">

2023-06-05 22:25 UTC, DavidPHH commented
Very nice addition with the Scrapper, deffinitely beats doing it manually.

A possible way to speed it up could maybe be by appending &xml to the link, e.g. `https://www.wowhead.com/item=194684&xml` to avoid fetching the entire page. And also maybe doing the whole thing within python instead of half manually with bash & python.  

Although no point in spending more time on it right now IMO, since new drinks are added so infrequently. This seems plenty good enough.

Thanks for the contributions 👍

2023-06-06 17:38 UTC, DavidPHH requested changes

2023-06-06 17:38 UTC, DavidPHH commented on DrinkMacroCreator.lua
> +
WoW's lua doesn't have table.move as far as i can see? Could you change this to something else please.

```suggestion
for i = #magefood, 1, -1 do
    table.insert(drinks, 1, magefood[i])
end
```

2023-06-07 11:38 UTC, EricaPomme commented
I tried the xml thing initially, it looked like it didn’t have all the information we needed in the page that was returned. 

This was one of those “banged it out for giggles while watching YouTube on the couch” things, so I’ll admit some laziness in the approach. I’ll take another swing at the scraper; the more I think about it, the more I’d rather just have a “push button, receive table” tool.

2023-06-07 21:12 UTC, EricaPomme commented
I gutted it and rebuilt it like I knew I should have in the first place. Sorry for wasting your time with the first PR. 😅

2023-06-09 20:47 UTC, DavidPHH approved these changes
Thank you!
LGTM

2023-06-09 20:47 UTC, merged